sudo: required
dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

env:
  global:
    - REAMQUERY_WORLDDB_NPGSQL='Server=localhost; User Id=postgres; Password=; Database=world'

before_install:
 - ulimit -n 1024
 # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
 - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 2.0.2 --install-dir ~/.dotnetcli
 - PATH="~/.dotnetcli:$PATH"

install:
 - dotnet --info
 - psql -c 'create database world;' -U postgres
 - psql -d world -U postgres -f $TRAVIS_BUILD_DIR/sql/world_postgresql.sql

script:
 - dotnet run -p tools/ReamQuery.RefDumper
 - dotnet test test/ReamQuery.Core.Test
 - dotnet test test/ReamQuery.Server.Test
