version: 0.1.0.{build}
branches:
  only:
    - master
services:
  - mssql2014

environment:
  CLI_VERSION: latest
  CLI_ARCH: x64
  DOTNETCLI_ZIP_URL: https://go.microsoft.com/fwlink/?LinkID=831469
  REAMQUERY_WORLDDB_SQLSERVER: Data Source=.\SQL2014; User Id=sa; Password=Password12!; Initial Catalog=world
  REAMQUERY_TYPETEST_SQLSERVER: Data Source=.\SQL2014; User Id=sa; Password=Password12!; Initial Catalog=typetest

install:
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Version 2.0.2"
  - dotnet --info

before_build:
  - ps: $sqlInstance = "(local)\SQL2014"
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -Q "use master; create database world;"
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -Q "use master; create database typetest;"
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -i $env:APPVEYOR_BUILD_FOLDER\sql\world_sqlserver.sql
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -i $env:APPVEYOR_BUILD_FOLDER\sql\typetest_sqlserver.sql

# need build_script, or appveyor starts looking for a sln file
build_script:
  - dotnet run -p tools\ReamQuery.RefDumper

test_script:
  - dotnet test test\ReamQuery.Core.Test
  - dotnet test test\ReamQuery.Server.Test
